# Generated by Django 3.1.2 on 2020-10-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='run_timedate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
